# Generated by Django 5.2.5 on 2025-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_rejected_user_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
